### ISSUE TITLE
Edit Shipment Panel ctrl+f issue

### ISSUE THREAD

**Issue by shroeder** [Navegate/Navegate#11]
Open, close the references panel, hit ctrl + f, type in a value that you know is inside the references panel :+1: 

![image](https://cloud.githubusercontent.com/assets/3152706/9262982/e6d82780-41de-11e5-8177-5feba5c9df56.png)

**Comment by sam-damico** [comment]
This seems to be a much wider issue with ctrl+f and the panels. Using ctrl+f and finding things that are in panels that aren't open causes problems all over the page. I am going to re-name this issue to be more general and try to figure out the root cause of this.

**Comment by sam-damico** [comment]
These are the panels that it seems to be happening in:
References
Relationships
Measurements
Transportation
Cargo
Items
Parties
Dates
Locations
Messages

It is difficult to see what is actually happening but it looks like things are being pushed up or down, usually in a different panel. Below is an example, this is using ctrl+F on something in measurements panel.


![shipment_panels_error](https://cloud.githubusercontent.com/assets/13786914/9337847/57a64b9c-45a7-11e5-9097-33a88bd1c845.JPG)

**Comment by shroeder** [comment]
I think whatever parent element it is being shown in needs to have a display of none, which it must be missing

**Comment by sam-damico** [comment]
Ok, so it looks like at some point the panels were getting their display set to none. But at some point that got commented out, it was a long time ago and I can't even see that revision in my svn log. 

For now, i have changed it to change the panels to display:none when they are closed, which fixes this issue. But I would like to figure out why the line was commented out in the first place.

**Comment by sam-damico** [comment]
Upon further inspection the Private panel was still doing this if you type "operator(s)" because of the way the private panel was laid out. I have made some changes that will fix this. Rev 3109

**Comment by shroeder** [comment]
Lets make it a point to test this extensively when we push 'Current Build'.  I'm going to add a new label to this bug.  Also, could you comment on the Private Panel fix a bit further?

**Comment by sam-damico** [comment]
Sounds good. The openpanel() function takes a variable that is an object name. When it opens or closes the panel it also shows or hides this object. Previously the object getting passed didn't include the whole content of the panel, basically everything but the "operator(s)" line. I gave the container element an id and changed all the openpanel() calls to use this new container id.
