### ISSUE TITLE
Charge Type Numeric Formatting

### ISSUE THREAD

**Issue by shroeder** [Navegate/Navegate#2]
The Charge Type lookup is Formatting money : 

Charges_v11.ascx  

Only happens when typing the value then selecting it from the drop down that comes up

![image](https://cloud.githubusercontent.com/assets/3152706/9262420/68fb1fce-41da-11e5-9cb4-50d9a96beb73.png)

**Comment by sam-damico** [comment]
charges_v11 is in an Electronic Air Waybill document

**Comment by sam-damico** [comment]
This appears to happen everywhere there is a call to DocumentsFormatMoney() in document.aspx.js.
The function loops through inputs that should format their value to money, but the way it is written means that the last event source element is getting formatted. I have changed it to ensure that only the inputs that are supposed to format do. Rev 3099
