### ISSUE TITLE
Error: Incorrect syntax near 'N'.

### ISSUE THREAD

**Issue by shroeder** [Navegate/Navegate#20]

**Comment by sam-damico** [comment]
Unclosed quotation mark after the character string ' ORDER BY p.ProductDesc'.

**Comment by shroeder** [comment]
Was this related to Unclosed quotation mark after the character string ' ORDER BY p.ProductDesc'. then?

**Comment by sam-damico** [comment]
Yeah, Loren's update to the Dataservice should fix this issue too. It looks like we got two different similar errors depending on what the user entered.
