### ISSUE TITLE
Unable to get property 'left' of undefined or null reference

### ISSUE THREAD

**Issue by shroeder** [Navegate/Navegate#32]

**Comment by sam-damico** [comment]
Error: 
Company Name:		North Star World Trade Services, Inc.
RegistrantID:		743
User Name:		Mario Acosta
RegistrantUserID:	5704
SiteRoot:		https://www.navegate.com/
Error Number:		-2146823281
Project ID:		1717905
Global Folder ID:		1270080
Error Description:		Error in pageLoad(sender, args) function.
Number: -2146823281
Name: TypeError
Description: Unable to get property 'left' of undefined or null reference
Location: folders/clientside/document.aspx.js
BroswerVersion: InternetExplorer11
ASPX Page: document.aspx

**Comment by sam-damico** [comment]
Description: Unable to get property 'left' of undefined or null reference
Location: folders/clientside/document.aspx.js

**Comment by sam-damico** [comment]
I am unable to replicate the error but I can see where it is happening. I have added a check to see if the object being referenced exists before assigning it's left value. Rev. 3096

**Comment by sam-damico** [comment]
I have now pulled out the old error handeling in the functions: slideSomething() and pageLoad(). Rev 3106
