### ISSUE TITLE
Error: -99 - Attachment cannot be deleted it is associated to a message

### ISSUE THREAD

**Issue by shroeder** [Navegate/Navegate#40]
Do we need to throw this as an error?

**Comment by sam-damico** [comment]
If we decide we don't need to throw it, that can changed. I think we should talk about it.

**Comment by shroeder** [comment]
I talked with Loren regarding this yesterday, and we decided to not throw this.  Could you make it so?

**Comment by sam-damico** [comment]
This is done, if the error message is "-99 - Attachment cannot...." the error is not sent to the WriteError() function, but it will still show the error popup to the user so they know what is going on. Rev -3105

**Comment by shroeder** [comment]
Perfect thank you
