### ISSUE TITLE
Leftover debug code in getItemsFromServer() in itemspanel.ascx.js

### ISSUE THREAD

**Issue by sam-damico** [Navegate/Navegate#43]
It looks like there is some code in this function that shouldn't be there (ex: alert('hello') in a catch block) and a few other places. I am going to remove them so users don't get strange alerts.

**Comment by sam-damico** [comment]
It is done. I also stripped out a ton of extra whitespace from this page and formatted some places to be easier to read. -Rev 3102

**Comment by shroeder** [comment]
Nice work picking up on that.  Sounds like a mighty fine change.
