### ISSUE TITLE
Click fails to redirect

### ISSUE THREAD

**Issue by shroeder** [Navegate/Navegate#6]
When clicking inside of a list item, header menus fail to be clicked until you actually click on the text : 

![image](https://cloud.githubusercontent.com/assets/3152706/9262768/158b9992-41dd-11e5-8f76-5a6b18807fb0.png)

**Comment by sam-damico** [comment]
This is now fixed. There was a css property of display:block that had been commented out by someone... It has now been un-commented. Rev 3104

**Comment by shroeder** [comment]
That a boy Sam
